# Generated by Django 5.0.7 on 2024-09-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usersignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('cpassword', models.CharField(max_length=20)),
                ('mobile', models.BigIntegerField()),
                ('dateofbirth', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('adhar', models.BigIntegerField()),
            ],
        ),
    ]
