# Generated by Django 5.0.7 on 2024-09-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_usersignup_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=20),
        ),
    ]
