# Generated by Django 5.0.7 on 2024-09-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_usersignup_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='gender',
            field=models.CharField(max_length=20),
        ),
    ]
