# Generated by Django 5.0.7 on 2024-09-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_usersignup_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True),
        ),
    ]
